"""
FAISS vector-index management for the Aster & Row knowledge base.

This module converts our internal DocumentChunk objects into LangChain
Document objects and stores them in a FAISS vector index.

The FAISS index is a derived artifact. The original Markdown knowledge-base
files remain unchanged and continue to be the authoritative source data.

Each indexed Document retains:
    - chunk content
    - filename
    - heading
    - original front-matter metadata
"""

from pathlib import Path

from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS

from app.rag.chunker import DocumentChunk
from app.rag.embeddings import get_embedding_model


def chunks_to_documents(
    chunks: list[DocumentChunk],
) -> list[Document]:
    """
    Convert application-level chunks into LangChain Documents.

    Metadata is preserved because retrieval and source citation depend on
    information that is not represented by the vector alone.
    """

    documents: list[Document] = []

    for chunk in chunks:
        metadata = {
            # Stable identifier used to trace a retrieved result back to
            # the exact chunk generated during indexing.
            "chunk_id": chunk.chunk_id,

            # Required for customer-facing source citations.
            "filename": chunk.filename,
            "heading": chunk.heading,

            # Preserve all original document front matter.
            **chunk.metadata,
        }

        documents.append(
            Document(
                page_content=chunk.content,
                metadata=metadata,
            )
        )

    return documents


def build_faiss_index(
    chunks: list[DocumentChunk],
) -> FAISS:
    """
    Build a FAISS index from document chunks.

    Args:
        chunks:
            Retrieval-ready chunks generated by the chunking pipeline.

    Returns:
        A LangChain FAISS vector store.
    """

    if not chunks:
        raise ValueError(
            "Cannot build FAISS index from an empty chunk collection."
        )

    documents = chunks_to_documents(chunks)

    embeddings = get_embedding_model()

    return FAISS.from_documents(
        documents=documents,
        embedding=embeddings,
    )


def save_faiss_index(
    vectorstore: FAISS,
    index_path: str | Path,
) -> None:
    """
    Persist a FAISS index to disk.

    The generated index is treated as a derived artifact and can be rebuilt
    from the original knowledge base whenever required.
    """

    path = Path(index_path)

    path.mkdir(
        parents=True,
        exist_ok=True,
    )

    vectorstore.save_local(str(path))


def load_faiss_index(
    index_path: str | Path,
) -> FAISS:
    """
    Load a previously generated FAISS index from disk.

    The embedding model must match the model used when the index was built.
    """

    path = Path(index_path)

    if not path.exists():
        raise FileNotFoundError(
            f"FAISS index directory does not exist: {path}"
        )

    embeddings = get_embedding_model()

    return FAISS.load_local(
        str(path),
        embeddings,
        allow_dangerous_deserialization=True,
    )